name: lint-test-runner
on: [push]
jobs:
  install-dependencies:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
        with:
         node-version: '14.15.3'
    - run: npm install
    - run: npm run type-check
